### ISSUE TITLE
No matching distribution found for traitlets>=5.0.0 (from co2mpas)

### ISSUE THREAD

**Issue by MaikeruJon** [JRCSTU/CO2MPAS-TA#12]
Upgrading from co2mpas -1.4.1 to co2mpas-1.5.5 using the console.
Error message
"Collecting traitlets>=5.0.0 (from co2mpas)
  Could not find a version that satisfies the requirement traitlets>=5.0.0 (from co2mpas) (from versions: 0.0.1, 0.0.2, 4.0.0.dev0, 4.0.0, 4.1.0b1, 4.1.0, 4.2.0, 4.2.1, 4.2.2, 4.3.0b1, 4.3.0, 4.3.1, 4.3.2)
No matching distribution found for traitlets>=5.0.0 (from co2mpas)
[console_output.docx](https://github.com/JRCSTU/CO2MPAS-TA/files/1073457/console_output.docx)"

**Comment by VictorValverde** [comment]
Dear @MaikeruJon thanks for using github.
[CO2MPAS 1.5.5](https://github.com/JRCSTU/CO2MPAS-TA/releases/tag/v1.5.5) was released with an accompanying All-in-One (ie, not only the CO2MPAS code was upgraded but also additional python libraries as triatlets). In order to use CO2MPAS 1.5.5 we recommend you to directly [download the All-in-One from its original source](https://github.com/JRCSTU/CO2MPAS-TA/releases/download/v1.5.5/co2mpas_AIO-v1.5.5.7z) and follow the [usual intstructions](https://co2mpas.io/install.html#all-in-one-installation-under-windows) to install it.
In order to remove the previous installation of CO2MPAS (1.4.1) you can simply delete its folder from your computer.

Please, write us back if you face any other problem during the upgrade or close the issue if the process ended well.
Regards, Victor

**Comment by MaikeruJon** [comment]
Hello Victor
Thanks for your support.
All is OK, according to your instructions. I note, however, that the install file is now a VB script, rather than a batch file, so maybe installation instructions need updating for that.
Regards
Michael

**Comment by VictorValverde** [comment]
Thanks, we will update the installation instructions accordingly!

**Comment by MaikeruJon** [comment]
Hello Victor

 

Is it OK for me to send an E-mail to you directly? If this is not
acceptable, please advise the correct procedure.

 

Thank you for your kind support for the CO2MPAS programme.

 

I am going through the notes from the workshop that was held on 15 May. I am
setting my computer up according to the following instructions:

 



 

But I encountered an error. Please see the attached console output.

 

Please help.

 

Thank you

 

Michael

**Comment by MaikeruJon** [comment]
Hello Victor

 

Please ignore this mail. 

 

I believe that the error was due to the file being in use.

 

The installation is now successful.

 

Best regards

 

Michael

 

From: VCA Michael J Mulvaney [mailto:michael@vca-asia.jp] 
Sent: Thursday, June 15, 2017 11:48 AM
To: 'JRCSTU/CO2MPAS-TA'
Subject: Upgrade CO2MPAS with additional features

 

Hello Victor

 

Is it OK for me to send an E-mail to you directly? If this is not
acceptable, please advise the correct procedure.

 

Thank you for your kind support for the CO2MPAS programme.

 

I am going through the notes from the workshop that was held on 15 May. I am
setting my computer up according to the following instructions:

 



 

But I encountered an error. Please see the attached console output.

 

Please help.

 

Thank you

 

Michael

**Comment by MaikeruJon** [comment]
Hello Victor

 

Can you please help me?

 

I have been working through the notes from the workshop held in May.
Unfortunately VCA was not told about the workshop so nobody from VCA
attended.

 

I would attach the notes to which I refer, but the pdf file is 4MB.

 

But the notes have been annotated, which is helpful.

 

I have progressed to item 11 on page 3; I confirmed the status of 'mailed'
for the project.

 

I receive an e-mail, attached.

 

When I run the command at item 12, I receive the error, attached.

 

I am not clear on what to do. I have reviewed the sample configuration files
from the web site, but I can find no answer. My e-mail account is set up as
POP, so I can't receive IMAP unless I set up a separate account.

 

I have attached my configuration file.

 

Please help.

 

Thanks

 

Michael

 


c.GpgSpec.master_key = 'CBBB52FF'

c.DiceSpec.user_email = "michael@vca-asia.jp"
c.DiceSpec.user_name = "michael@vca-asia.jp"

c.LoginCmd.srv = 'SMTP'
c.TstampSender.user_email = "michael@vca-asia.jp"
c.TstampSender.user_name = "michael@vca-asia.jp"
c.TstampSender.host = "mail01.vserverhosts.com"
c.TstampSender.port = 465
c.TstampSender.ssl = 'SSL/TLS'

c.TstampReceiver.user_email = "michael@vca-asia.jp"
c.TstampReceiver.user_name = "michael@vca-asia.jp"
c.TstampReceiver.host = "mail01.vserverhosts.com"
c.TstampReceiver.port = 995
c.TstampReceiver.ssl = 'SSL/TLS'

c.TstampSender.subject_prefix = "[dice test]"
c.TstampSender.tstamper_address = "post@stamper.itconsult.co.uk"

c.TstampSender.tstamp_recipients = [
    "JRC-CO2MPAS@ec.europa.eu",
    "CLIMA-LDV-CO2-CORRELATION@ec.europa.eu",
    ]

c.TstampSender.cc_addresses = [
   "michael@vca-asia.jp", # EMAIL (QUOTED)
    ]

**Comment by dimitriskomnos** [comment]
Dear @MaikeruJon,

The version you use must be the 1.5.5.post0. Is this right? 
For this version the command you typed 
```
co2dice tstamp recv --raw
```
should not work,
since it is a new feature that the upcoming releases will have. I was just introduced in the WorkShop was held on May. 

So, in case that you use the 1.5.5.post0, and you have received the response from the Time Stamper, please proceed with this:
1. Open the email that you received and copy the response (from -----BEGIN PGP SIGNED MESSAGE----- to the end) 
2. In the console type:
```
co2dice project tparse
```
3.  Now paste it in the console by pressing ``[Shift+INSERT]``, and send the end-stream character after a new-line, that is to say: press ``[Enter]``, ``[Ctrl+Z]``, ``[Enter]``, in a row.

The dice stamp should be decoded showing at the end of the message the random sampling number [0 to 99], and the OK/SAMPLE decision-flag. 

Please reply back if the procedure went fine, or you still face problems. 
Kind regards,
Dimitris.
