### ISSUE TITLE
Analysis standard for fuel values

### ISSUE THREAD

**Issue by MaikeruJon** [JRCSTU/CO2MPAS-TA#19]
Hello
As for the following required input data:
'Fuel lower heating value'
'Fuel carbon content'
What is the expected standard by which these values should be determined?
Frankly speaking, I have no idea how the values might vary according to the measurement by different standards, but I was asked this question and I would be very grateful if someone can kindly advise me on this matter.

**Comment by gfon** [comment]
Dear @MaikeruJon 

Since [EN590](http://www.envirochem.hu/www.envirochem.hu/documents/EN_590_2009_hhV05.pdf) and [EN228](http://www.envirochem.hu/www.envirochem.hu/documents/EN_228_benzin_JBg37.pdf) do not foresee any specification for these two characteristics there is no expected standard that we can think of and the correlation legislation does not name one. Any established, standardized measurement method used by the certified lab that does the analysis of the fuel can be accepted.  There are numerous standards that might be used for the measurements of such fuel properties (indicatively without suggesting a specific one and intention to exclude others J1498, ASTM D5291, ASTM D4809, ASTM D3338, ASTM D3343, ASTM D240). At this point we remind that in CO2MPAS the **net (lower)** heating value of the fuel shall be used as input.

**Comment by MaikeruJon** [comment]
Thanks for this reply by return. Much appreciated. And thanks for the links.
