### ISSUE TITLE
CO2MPAS Input file - WLTP retest values

### ISSUE THREAD

**Issue by kwzsn** [JRCSTU/CO2MPAS-TA#42]
Hi,

In the CO2MPAS input file version 3.0.1, in row 6, WLTP re-test values need to be selected from the drop down menu. Could you let me the know where I can find more information regarding the values available? I can't find the paragraph 2.2b of Annex I in the regulation

Thanks

**Comment by sapofra** [comment]
Dear @kwzsn user,

here https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02017R1153-20190201&from=EN you can find the information you are looking for (page 10-11).
The drop-down menu presents not only a/b/c/d options but also their combinations in case that more than one condition applies. 
Let us know if you need further support, otherwise please close the issue.

Kind regards.
