### ISSUE TITLE
COMPAS 4.1.10 Drive Battery voltage

### ISSUE THREAD

**Issue by albertoleon86** [JRCSTU/CO2MPAS-TA#47]
Is it mandatory to introduce the measurement of the voltage of the Drive Battery (for OVC PHEV)? As I understand you can choose to work with Nominal Voltage ( annex XV, Sub annex 8, app3 point 3.2

**Comment by tansial** [comment]
Correct, nominal voltage can in principle be provided instead of the measured battery voltage timeseries.
Unfortunately, due to an inconsistency in the input scheme, a timeseries is still required and we are sorry that this is something we cannot solve at this stage.
Furthermore, the data inserted in the drive_battery_voltages column cannot be a fixed value pasted to all the cells.
 
When the data insertion is carried out to perform vehicle type-approval, we strongly prefer that the real measured value is provided, but in case you don't have such a signal there is the workaround you can adopt.
You can simply write a formula in the cells of drive battery voltage and create a linear dependency with the drive battery current as follows:

drive battery voltage = battery_nominal_voltage + 0.01 * drive battery current

Please, let us know whether this does not solve your doubt/problem, otherwise please close the issue.
Best regards.
